service: backend-qldb


provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

functions:
  hello:
    handler: functions/hello.handler

resources:
  - ${file(resources/cognito-user-pool.yml)}
