Resources:
  cognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: "#{AWS::StackName}-userpool"
      AutoVerifiedAttributes:
        - email     

  cognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref cognitoUserPool
      ClientName: "#{AWS::StackName}-userpoolclient"